#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  red1,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  red2,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  green1,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl4,  green2,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl5,  button1,        sensorTouch)
#pragma config(Sensor, dgtl6,  button2,        sensorTouch)
#pragma config(Sensor, dgtl11, red3,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, red4,           sensorLEDtoVCC)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           baseRotation,  tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           baseLift,      tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           elbowLift,     tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port4,           handLift,      tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port5,           handRotation,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           handClaw,      tmotorVex393_MC29, openLoop)
#pragma config(DatalogSeries, 0, "I2C Encoder 1 - Base Rotation", Sensors, Sensor, I2C_1, 10)
#pragma config(DatalogSeries, 1, "I2C Encoder 2 - Base Lift", Sensors, Sensor, I2C_2, 10)
#pragma config(DatalogSeries, 2, "I2C Encoder 3 - Elbow Lift", Sensors, Sensor, I2C_3, 10)
#pragma config(DatalogSeries, 3, "I2C Encoder 4 - Hand Lift", Sensors, Sensor, I2C_4, 10)
#pragma config(DatalogSeries, 4, "I2C Encoder 5 - Hand Rotation", Sensors, Sensor, I2C_5, 10)
#pragma config(DatalogSeries, 5, "I2C Encoder 6 - Claw", Sensors, Sensor, I2C_6, 10)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* 
	                              
                                                            

                      _____          ___         _____       
                     |__  /         <  /        /__  /       
                      /_ <          / /           / /  ______
                    ___/ /   _     / /   _       / /  /_____/
                   /____/   (_)   /_/   (_)     /_/          
                                                             
           _____                  _            __   ___                 
          / ___/__  ___________ _(_)________ _/ /  /   |  _________ ___ 
          \__ \/ / / / ___/ __ `/ / ___/ __ `/ /  / /| | / ___/ __ `__ \
         ___/ / /_/ / /  / /_/ / / /__/ /_/ / /  / ___ |/ /  / / / / / /
        /____/\__,_/_/   \__, /_/\___/\__,_/_/  /_/  |_/_/  /_/ /_/ /_/ 
                        /____/                                          
						
                   /`   | _  |    |_|      . _   |).   _   ,_
                   \,()(|(/_ |)\/ | |(||`|`|(/_|`| |(|(/_()||
                               /                    _|    			
					   			                          
 */
/* in Visual Studio Code, commenting out a multiline block  is Shift+Alt+A. */
// In the RobotC IDE, the shortcut is Ctrl-Q.


//DECLARING "STATIC" VARIABLES FOR MATH STUFF

// Creating structures for organization, cleanliness, and anti-brain-crash measures.



struct MotorCalibrationControlStructure {
	/* 	 these two are the limit switches that mark the end of the arm's rotation in that direction. */
	int lowerLimitPort;	
	int upperLimitPort;  


};

struct MotorControlStructure 		// (StructureName)
{
	int motorPort;								// (StructureName).motorPort
	int encoderPort;							// (StructureName).encoderPort
	int gearRatio;								// (StructureName).gearRatio
	int encoderCalibrationValue;	// (StructureName).encoderCalibrationValue
};


struct ArmLengthMathSubStructure // (struct RobotArmControlStructure name).(struct ArmLengthMathSubStructure).XXX
{
	 float length;
	 float height;
	 float MA;
	 float angleA;
	 float lengthA;
	 float angleB;
	 float lengthB;
	 float angleC;
	 float lengthC;

};

struct RobotArmControlStructure
{
	struct MotorControlStructure shoulder;
	struct MotorControlStructure elbow;
	struct MotorControlStructure wrist;
	struct ArmLengthMathSubStructure lengthMath;

};




task main()
{

}
