#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_6,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           baseRotation,  tmotorVex393_HBridge, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port2,           baseLift,      tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port3,           elbowLift,     tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port4,           handLift,      tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port5,           handRotation,  tmotorVex393_MC29, openLoop, encoderPort, I2C_5)
#pragma config(Motor,  port6,           handClaw,      tmotorVex393_MC29, openLoop, encoderPort, I2C_6)
#pragma config(DatalogSeries, 0, "I2C Encoder 1 - Base Rotation", Sensors, Sensor, I2C_1, 10)
#pragma config(DatalogSeries, 1, "I2C Encoder 2 - Base Lift", Sensors, Sensor, I2C_2, 10)
#pragma config(DatalogSeries, 2, "I2C Encoder 3 - Elbow Lift", Sensors, Sensor, I2C_3, 10)
#pragma config(DatalogSeries, 3, "I2C Encoder 4 - Hand Lift", Sensors, Sensor, I2C_4, 10)
#pragma config(DatalogSeries, 4, "I2C Encoder 5 - Hand Rotation", Sensors, Sensor, I2C_5, 10)
#pragma config(DatalogSeries, 5, "I2C Encoder 6 - Claw", Sensors, Sensor, I2C_6, 10)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{



}
