#pragma config(Sensor, dgtl5,  button2,        sensorTouch)\
#pragma config(Sensor, dgtl6,  button,         sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

struct TEST {
	int buttonPort;
	int button2Port;
};


void initializeTestStruct(struct TEST test1)
{
	test1.buttonPort = 13;
	test1.button2Port = button2;
	//return test1;
}

void useTestStruct(struct TEST BOOP)
{
		writeDebugStreamLine("button's readout is %d, by grabbing from dgtl6 = 13 is %d, structure for button 1 is %d, structure for button 2 is %d", SensorValue[button],SensorValue[13],SensorValue[BOOP.buttonPort],SensorValue[BOOP.button2Port]);
}

task main()
{
	struct TEST TESTBOOPTEST;
	initializeTestStruct(TESTBOOPTEST);

	while(0!=1) {
		useTestStruct(TESTBOOPTEST);
	//writeDebugStreamLine("button's readout is %d, by grabbing from dgtl6 = 13 is %d, structure for button 1 is %d, structure for button 2 is %d", SensorValue[button],SensorValue[13],SensorValue[test1.buttonPort],SensorValue[test1.button2Port]);
	waitInMilliseconds(10);

	}

}
